---
- name: Restart nut-server
  ansible.builtin.systemd:
    name: nut-server
    state: restarted

- name: Restart nut-monitor
  ansible.builtin.systemd:
    name: nut-monitor
    state: restarted

- name: Restart nut-driver
  ansible.builtin.systemd:
    name: "nut-driver@{{ item.name }}"
    state: restarted
  loop: "{{ ups_devices }}"
  retries: 5
  delay: 5
  register: _nut_driver_restart  # noqa: var-naming[no-role-prefix]
  until: _nut_driver_restart is not failed
  ignore_errors: true

- name: Reload udev rules
  ansible.builtin.shell:
    cmd: udevadm control --reload-rules && udevadm trigger --subsystem-match=usb
  changed_when: false
